project_id = "psxskwerldhfjmanzbpk"

[functions.notion-sync]
verify_jwt = false

[functions.export-lead-to-csv]
verify_jwt = false

[functions.assessment-hubspot-sync]
verify_jwt = false

[functions.hubspot-retry-sync]
verify_jwt = false

[functions.backfill-cvss]
verify_jwt = false

[functions.sync-github-pocs]
verify_jwt = false

[functions.threat-intel]
verify_jwt = false

[functions.send-alert]
verify_jwt = false

[functions.crm-sync-monitor]
verify_jwt = false

[functions.github-proxy]
verify_jwt = false

[functions.zoom-meetings]
verify_jwt = false

[functions.zoom-oauth-callback]
verify_jwt = false

[functions.gh]
verify_jwt = false
