// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psxskwerldhfjmanzbpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzeHNrd2VybGRoZmptYW56YnBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NDU3NDQsImV4cCI6MjA4NzAyMTc0NH0.gweEX9iktbtIW_En991lHbHhMrf51_V6zqmUB3C7TYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});